// Generates the session.v1 types for C# and TypeScript (ST-003).
//
// TypeScript comes from json-schema-to-typescript. C# comes from the small generator below: immutable
// records with `required` members and System.Text.Json polymorphism for the event union, which the
// off-the-shelf generators don't produce and which the client's analyzers (warnings as errors) accept.
// It supports exactly the schema subset session.v1 uses and throws on anything else, so a schema change
// it can't express fails loudly instead of generating something subtly wrong. Validation-only keywords
// (if/then/else, minimum, minLength, formats other than date-time) don't affect the types.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const schemaFile = resolve(here, '../session.v1.json');
const targets = {
  csharp: resolve(repoRoot, 'client/ScreenTail.Shared/Generated/SessionV1.g.cs'),
  typescript: resolve(repoRoot, 'web/src/generated/session.v1.ts'),
};
const banner =
  'Generated from shared/schema/session.v1.json by shared/schema/codegen/generate.mjs. ' +
  'Do not edit by hand: change the schema and run `npm run codegen` in shared/schema.';

// $defs of the schema being generated; set by csharp() and read by its helpers.
let defs = {};

const schema = JSON.parse(await readFile(schemaFile, 'utf8'));
await emit(targets.typescript, await typescript(schema));
await emit(targets.csharp, csharp(schema));

async function emit(file, text) {
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, text.endsWith('\n') ? text : `${text}\n`);
  console.log(`wrote ${relative(repoRoot, file)}`);
}

// ---- TypeScript -------------------------------------------------------------------------------------

function typescript(root) {
  return compile(structuredClone(root), 'Session', {
    bannerComment: `/* ${banner} */`,
    additionalProperties: false,
    unreachableDefinitions: true,
    format: true,
    style: { singleQuote: true },
  });
}

// ---- C# ---------------------------------------------------------------------------------------------

function csharp(root) {
  defs = root.$defs ?? {};
  const unionMembers = new Map();
  for (const [name, def] of Object.entries(defs)) {
    if (!def.oneOf) continue;
    const hoisted = commonRequired(unionOf(name));
    for (const member of unionOf(name)) {
      unionMembers.set(member, { base: name, skip: new Set(['type', ...hoisted]) });
    }
  }

  const w = writer();
  w('// <auto-generated>');
  w(`// ${banner}`);
  w('// </auto-generated>');
  w('#nullable enable');
  w('');
  w('using System.Text.Json.Serialization;');
  w('');
  w('namespace ScreenTail.Shared.Schema;');

  record(w, root.title ?? 'Session', root, null, new Set());
  for (const [name, def] of Object.entries(defs)) {
    if (def.enum) {
      enumType(w, name, def);
    } else if (def.oneOf) {
      unionBase(w, name, def);
    } else if (def.type === 'object') {
      const member = unionMembers.get(name);
      record(w, name, def, member?.base ?? null, member?.skip ?? new Set());
    } else if (!isPrimitiveAlias(def)) {
      throw new Error(`$defs.${name}: unsupported definition`);
    }
  }

  return w.text();
}

function unionOf(name) {
  return defs[name].oneOf.map((m) => refName(m.$ref, `${name}.oneOf`));
}

function unionBase(w, name, def) {
  const members = unionOf(name);
  const hoisted = commonRequired(members);
  w('');
  summary(w, def.description, '');
  w('[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]');
  for (const member of members) {
    const discriminator = defs[member].properties?.type?.const;
    if (typeof discriminator !== 'string') {
      throw new Error(`${member}: union members need a string "type" const`);
    }
    w(`[JsonDerivedType(typeof(${member}), "${discriminator}")]`);
  }
  w(`public abstract record ${name}`);
  w('{');
  hoisted.forEach((prop, i) => {
    if (i > 0) w('');
    property(w, prop, defs[members[0]].properties[prop], true, `${name}.${prop}`);
  });
  w('}');
}

// Properties required by every union member with an identical schema move to the base record.
function commonRequired(members) {
  const [first, ...rest] = members.map((m) => defs[m]);
  return (first.required ?? []).filter(
    (prop) =>
      prop !== 'type' &&
      rest.every(
        (d) =>
          (d.required ?? []).includes(prop) &&
          JSON.stringify(d.properties?.[prop]) === JSON.stringify(first.properties?.[prop]),
      ),
  );
}

function record(w, name, def, base, skip) {
  if (def.type !== 'object' || def.additionalProperties !== false) {
    throw new Error(`${name}: objects must be "type": "object" with "additionalProperties": false`);
  }
  const required = new Set(def.required ?? []);
  const props = Object.entries(def.properties ?? {}).filter(([prop]) => !skip.has(prop));
  const heading = `public sealed record ${name}${base ? ` : ${base}` : ''}`;

  w('');
  summary(w, def.description, '');
  if (props.length === 0) {
    w(`${heading};`);
    return;
  }
  w(heading);
  w('{');
  props.forEach(([prop, ps], i) => {
    if (i > 0) w('');
    property(w, prop, ps, required.has(prop), `${name}.${prop}`);
  });
  w('}');
}

function property(w, json, ps, isRequired, where) {
  const target = ps.$ref ? defs[refName(ps.$ref, where)] : undefined;
  summary(w, ps.description ?? (target && isPrimitiveAlias(target) ? target.description : undefined), '    ');
  w(`    [JsonPropertyName("${json}")]`);
  if ('const' in ps) {
    if (typeof ps.const !== 'string') throw new Error(`${where}: only string consts are supported`);
    // `required` makes System.Text.Json reject a document that omits the property; the initializer
    // gives code the right value. Validation of the value itself is SessionValidator's job.
    w(`    public ${isRequired ? 'required ' : ''}string ${pascal(json)} { get; init; } = "${ps.const}";`);
    return;
  }
  const { type, nullable } = csType(ps, where);
  if (!isRequired) w('    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]');
  const optional = nullable || !isRequired;
  w(`    public ${isRequired ? 'required ' : ''}${type}${optional ? '?' : ''} ${pascal(json)} { get; init; }`);
}

function csType(ps, where) {
  if (ps.$ref) {
    const name = refName(ps.$ref, where);
    const target = defs[name];
    return isPrimitiveAlias(target) ? csType(target, where) : { type: name, nullable: false };
  }
  if (ps.enum || ps.oneOf || ps.anyOf || ps.allOf) {
    throw new Error(`${where}: use a $defs entry for enums and unions`);
  }
  let type = ps.type;
  let nullable = false;
  if (Array.isArray(type)) {
    const rest = type.filter((t) => t !== 'null');
    if (rest.length !== 1 || type.length !== 2) throw new Error(`${where}: unsupported type ${JSON.stringify(type)}`);
    [type] = rest;
    nullable = true;
  }
  switch (type) {
    case 'string':
      return { type: ps.format === 'date-time' ? 'DateTimeOffset' : 'string', nullable };
    case 'integer':
      return { type: 'long', nullable };
    case 'number':
      return { type: 'double', nullable };
    case 'boolean':
      return { type: 'bool', nullable };
    case 'array':
      return { type: `IReadOnlyList<${csType(ps.items, `${where}[]`).type}>`, nullable };
    default:
      throw new Error(`${where}: unsupported type ${JSON.stringify(ps.type)}`);
  }
}

function enumType(w, name, def) {
  if (!def.enum.every((v) => typeof v === 'string')) throw new Error(`${name}: only string enums are supported`);
  w('');
  summary(w, def.description, '');
  w(`[JsonConverter(typeof(JsonStringEnumConverter<${name}>))]`);
  w(`public enum ${name}`);
  w('{');
  def.enum.forEach((value, i) => {
    if (i > 0) w('');
    w(`    [JsonStringEnumMemberName("${value}")]`);
    w(`    ${pascal(value)},`);
  });
  w('}');
}

function isPrimitiveAlias(def) {
  return ['string', 'integer', 'number', 'boolean'].includes(def.type) && !def.enum;
}

function refName(ref, where) {
  const match = /^#\/\$defs\/([A-Za-z][A-Za-z0-9]*)$/.exec(ref ?? '');
  if (!match || !defs[match[1]]) throw new Error(`${where}: unsupported $ref ${ref}`);
  return match[1];
}

function pascal(text) {
  return text
    .split(/[_\-\s]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function summary(w, text, indent) {
  if (!text) return;
  w(`${indent}/// <summary>`);
  for (const line of wrap(escapeXml(text), 100)) w(`${indent}/// ${line}`);
  w(`${indent}/// </summary>`);
}

function escapeXml(text) {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function wrap(text, width) {
  const lines = [];
  let current = '';
  for (const word of text.split(/\s+/)) {
    if (current && current.length + word.length + 1 > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function writer() {
  const lines = [];
  const w = (line) => lines.push(line);
  w.text = () => `${lines.join('\n')}\n`;
  return w;
}
